// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8I_I60D6QiZuKDySnHIwOthuUA5MfPOo',
    appId: '1:947322010857:web:eaefd18260fd4d2b7d4478',
    messagingSenderId: '947322010857',
    projectId: 'sae-mobile-46d8c',
    authDomain: 'sae-mobile-46d8c.firebaseapp.com',
    storageBucket: 'sae-mobile-46d8c.appspot.com',
    measurementId: 'G-DZCQXYQBCW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxsJuKNIXQJ-gs13cAOjS5I6iC_nkQ3Zo',
    appId: '1:947322010857:android:5a927b37993377cc7d4478',
    messagingSenderId: '947322010857',
    projectId: 'sae-mobile-46d8c',
    storageBucket: 'sae-mobile-46d8c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7PsTCATGMpmMGjwqtxIIw2HK3j15b3L8',
    appId: '1:947322010857:ios:59a1c28b37ee53577d4478',
    messagingSenderId: '947322010857',
    projectId: 'sae-mobile-46d8c',
    storageBucket: 'sae-mobile-46d8c.appspot.com',
    iosClientId: '947322010857-6qpp5o3fke30mn4k0hqcqod4c1cucm3o.apps.googleusercontent.com',
    iosBundleId: 'com.example.saeMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7PsTCATGMpmMGjwqtxIIw2HK3j15b3L8',
    appId: '1:947322010857:ios:59a1c28b37ee53577d4478',
    messagingSenderId: '947322010857',
    projectId: 'sae-mobile-46d8c',
    storageBucket: 'sae-mobile-46d8c.appspot.com',
    iosClientId: '947322010857-6qpp5o3fke30mn4k0hqcqod4c1cucm3o.apps.googleusercontent.com',
    iosBundleId: 'com.example.saeMobile',
  );
}
